[package]
name = "holography"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.release]
lto = true

[profile.test]
opt-level = 3

[dependencies]
ndarray = { version = "0.15.6", features = ["rayon"] }
num = "0.4.0"
rayon = "1.6.1"
